ship-world: "world"
ship:
  speed: 0.1
  rotation-speed: 0.01      # Чем меньше это число (например, 0.03), тем плавнее поворот корабля.
  seat-offset-y: 0.5        # На сколько блоков поднять игрока над базовым сиденьем (0.0=дно блока)
  seat-center-xz: 0.5       # Добавка 0.5 центрирует сиденье внутри блока 1x1
  arrival-radius: 1.0    # За сколько блоков начинать поворот к следующей точке
  yaw-offset: 0.0       # Твой поворот модели (был 90.0)
  schematic-name: "shipbig3_rotated5.schem"
  motor-enabled: true
  motor-volume: 0.6
  motor-pitch: 0.4
  wheel:
    axis: "x"              # Было "z", при повороте на 90° стала "x"
    center-x: -1.0         # Новые координаты центра оси после поворота
    center-y: -1.0
    center-z: -6.0        # Координата Z, если колесо сместилось туда
effects:
  water_bubbles_amount: 1  # По 1 пузырьку за тик
  smoke_amount: 1          # 1 струйка дыма
  lantern_glow_amount: 1   # Было 5-10, ставим 1 (минимум для видимости)
  frog_glow_amount: 2      # Лягушка будет лишь слегка подсвечиваться при кваканье
  music_note_amount: 1  # Количество нот за один раз
  music_note_chance: 0.01 # Шанс появления (0.1 = 10% шанс каждый тик)
  frog_ambience_chance: 0.00005
ship-start-delay: 30
dj-seat:
  offset-x: 0.5
  offset-y: -0.9
  offset-z: 0.5
  yaw: 180.0
ship-route:
  - {x: 302218, y: 64, z: 40688}
  - {x: 302139, y: 64, z: 40404}
  - {x: 302655, y: 64, z: 40570}