name: FrogShip
version: '1.0-SNAPSHOT'
main: AlexTro.frogShip.FrogShip
api-version: '1.21'
depend: [WorldEdit]
commands:
  frogship:
    description: "Справка по командам FrogShip"
    usage: "/frogship"
    aliases: [fs, ship, froghelp]
  spawnship:
    description: Заспавнить корабль.
    usage: /spawnship <x> <y> <z>
  sitonship:
    description: Сесть на корабль.
  sitoff:
    description: "Слезть с корабля"
  spawnfrogs:
    description: "Заспавнить лягушек на бамбуковые сиденья"
  rmship:
    description: "Удалить текущий корабль"
  spawnjason:
    description: Призывает Пашкета и включает музыку.
  embark:
    description: "Посадить игрока на корабль (для КБ)"
    usage: "/embark <player>"
  audioship:
    description: "Включить музыку игроку"
    usage: "/audioship <player>"
  stopaudioship:
    description: "Остановить вещание для игрока"
    usage: "/stopaudioship [player]"
  reload_shipconf:
    description: "Перезагрузить конфигурацию плагина"